### ISSUE TITLE
Support Purge instance

### ISSUE THREAD

**Issue by shreyas-gopalakrishna** [microsoft/durabletask-netherite#141]
- Update the NetheriteOrchestrationService class to Implement the IOrchestrationServicePurgeClient interface and map it to the existing [PurgeInstanceHistoryAsync](https://github.com/microsoft/durabletask-netherite/blob/b30ad474d29823b023b1c37d2f23ff86c5b1b25f/src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs#L696) method.

Reference: https://github.com/microsoft/durabletask-java/issues/10
Sample Implementation PR for AzureStorageOrchestractionService: https://github.com/Azure/durabletask/pull/704

**Comment by sebastianburckhardt** [comment]
Makes sense. I suppose we just need to wait for the `IOrchestrationServicePurgeClient` to become available, which looks like it will happen in the next package release of DurableTask.Core.
