### ISSUE TITLE
Documentation Status is not up to date

### ISSUE THREAD

**Issue by Greg-Hitchon** [microsoft/durabletask-netherite#214]
Just an FYI the status section of the documentation seems to be lagging a release or 2:
![image](https://user-images.githubusercontent.com/3837138/211617775-eab85fe7-b741-4077-a5e7-0138cbb26800.png)

**Comment by sebastianburckhardt** [comment]
Thanks for letting us know, @Greg-Hitchon! Fixed now.

**Comment by davidmrdavid** [comment]
@sebastianburckhardt: should we close this issue now that it's been addressed?

**Comment by sebastianburckhardt** [comment]
Yes.
