### ISSUE TITLE
Part11 discarded ActivityWorkItem 11A19122 because partition was terminated

### ISSUE THREAD

**Issue by jbarntish** [microsoft/durabletask-netherite#289]
Hello,

We keep seeing issues when pulling files from SFTP in an activity. The process completes, but then it seems the orchestration execution dies immediately after and restarts, then it goes into this cycle for a bit before the orchestration ultimately dies.

The activity code isn't doing anything special:
- Opens SFTP connection
- Pulls file bits from SFTP
- Closes the connection
- Pushes bits to blob storage

The file isn't huge, maybe 100Mb. The bits do not leave the context of the activity. The file download does make it to blob storage and the activity ultimately completes successfully as indicated in the logs and the fact that the blob is stored.

The orchestration is running on an EP1 with scale-out set to 10. At the time this runs, there's only 1 orchestration and 1 activity running. Its purposely single-threaded to keep memory and external connections in check.

Any thoughts?

> SftpPollingOrchestrator: Function 'DownloadTrapFile (Activity)' started. IsReplay: False. Input: (1884 bytes). State: Started. HubName:
> 
> Task hub worker started. Latency: 00:00:02.0061949. Extension GUID 8ebdb0d0-4ca5-4195-a2a3-0ce2d4dab2b1. InstanceId: . Function: . 
> 
> Starting task hub worker. Extension GUID 8ebdb0d0-4ca5-4195-a2a3-0ce2d4dab2b1. InstanceId: . Function: . HubName:
> 
> Durable extension configuration loaded: {"httpSettings":{"defaultAsyncRequestSleepTimeMilliseconds":30000},"hubName":"specgen","storageProvider":{"KeepInstanceIdsInMemo
> 
> Using the Netherite storage provider.
> 
> Part11 discarded ActivityWorkItem 11A19122 because partition was terminated; instanceId=SftpPollingOrchestrator replacedBy=
> 
> SftpPollingOrchestrator: Function 'DownloadTrapFile (Activity)' completed. ContinuedAsNew: False. IsReplay: False. Output: (null). State: Completed
Executed 'DownloadTrapFile' (Succeeded, Id=6ec118ff-66ac-4730-a765-5a71cc048678, Duration=114198ms)

**Comment by jbarntish** [comment]
Worth noting: the orchestration is a single instance (re-uses the same instance id) and is eternal. It constantly re-schedules itself after a specific wait time.

Bringing this up because if there's some kind of memory leak in the orchestration instance somehow this might explain why we can download these 100MB files for a while and then at certain point it dies.

**Comment by sebastianburckhardt** [comment]
First, let me clarify that this warning:
> Part11 discarded ActivityWorkItem 11A19122 because partition was terminated
does not indicate a problem. It just means that the activity was interrupted due to a partition shutdown. In such cases, the activity will just restart automatically once the partition has restarted.

> but then it seems the orchestration execution dies immediately after and restarts, then it goes into this cycle for a bit before the orchestration ultimately dies.

What exactly are you seeing here? How does the orchestration die? Any error messages or status information?

>  It constantly re-schedules itself after a specific wait time.

Are you using continue-as-new? Otherwise, a constant rescheduling may cause issues due to large orchestration histories.
