### ISSUE TITLE
.Net function app error once deployed

### ISSUE THREAD

**Issue by vany0114** [microsoft/durabletask-netherite#294]
I have a .Net 6 function app using Netherite which locally works as expected, but once I deployed it shows this error however it is up and running, and apparently working fine. 

During the CD I publish the bits using the `win-x64` as the runtime identifier, something like:

```
dotnet publish path --configuration release --output outputPath --self-contained false --runtime win-x64
```

I also have this property set in the project file (I've tried with and without it and there's no difference):

```
<PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
</PropertyGroup>

```

### Func app error
![image](https://github.com/microsoft/durabletask-netherite/assets/12032625/f8bd1c82-19e7-45a3-905d-f4e182bf1870)

### Func app processing requests 
![image](https://github.com/microsoft/durabletask-netherite/assets/12032625/1a9cf082-7b32-4a88-8abb-fb0d017c48ff)

**Comment by kevinp** [comment]
We would really appreciate assistance on this! ☝🏼

**Comment by vany0114** [comment]
Closing this since that error somehow is gone.
