### ISSUE TITLE
Netherite scaling not working on consumption plan

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#336]
Tested a deployment on a consumption plan today and it appears that for some reason the scaling is not working.

The following query
```
// look for scale controller events
database("wawsprod").ScaleControllerEvents
| where PreciseTimeStamp > datetime(2023-12-18 12:00:00) 
| where SiteName== "functionssb3"
| project PreciseTimeStamp, Level, TaskName, Message
| where * contains "Durable"
| sort by PreciseTimeStamp asc 
```

shows that the wrong provider is being used (Azure Storage instead of Netherite):

*Using Durable storage provider type AzureStorage*

This may be a result of using the new Target-based Scaling algorithm.

**Comment by davidmrdavid** [comment]
We weren't able to repro this. Please see the internal thread. Maybe this is a transient deployment issue?

**Comment by sebastianburckhardt** [comment]
I tested this again and it seems to work now.
