### ISSUE TITLE
partitions become unresponsive because recovery hangs after reading object log

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#343]
Last week we were able to successfully track down a bug that can cause partitions to become unresponsive.

Specifically, the partition hangs during recovery, after reading the object log.

The problem lies with the recovery code for FASTER.
This is a known bug for FASTER that was fixed a while back (https://github.com/microsoft/FASTER/commit/a6c0dfa5f96dc0349987b3035e73fe90faddbfa4)
but Netherite is still on an old release.

To address this we created a patch release 2.0.23 
https://github.com/microsoft/FASTER/tree/sburckha/patchrelease-2.0.23

and we have updated the Netherite dev branch to point to this release (https://github.com/microsoft/durabletask-netherite/pull/264) so this fix will be picked up with the next release.

**Comment by alexjebens** [comment]
Is this supposed to help recover corrupt partitions or prevent future Corruption?

I tested it and I was unable to recover a corrupt state.

**Comment by alexjebens** [comment]
Corruption occured despite having manuall installed the 2.0.23 dependency

**Comment by sebastianburckhardt** [comment]
> Is this supposed to help recover corrupt partitions or prevent future Corruption?
The specific bug we fixed in this PR was not caused by corruption but by a bug in the recovery code, so it is recovering "corrupt" partitions.

> I tested it and I was unable to recover a corrupt state.
We have analyzed more reported cases of corruption and there appear to be root causes other than what was fixed in this PR. We are still investigating those.

**Comment by sebastianburckhardt** [comment]
We are currently suspecting that this corruption is caused by a bug that was fixed in the latest FASTER. Therefore we are not prioritizing updating Netherite to use the latest FASTER version. This work is tracked #344.
