### ISSUE TITLE
Question about performance warning logs

### ISSUE THREAD

**Issue by kvattikuti** [microsoft/durabletask-netherite#359]
I have been noticing these warnings in logs when I am testing. 
Category: `DurableTask.Netherite.FasterStorage.Performance`
Message: `Part00 Performance issue detected: storage operation BlockBlobClient.OpenWrite (WriteIndexCheckpointMetadata) took 2.2s on attempt 1, which is excessive; token=241a918f-9afe-4a51-b78e-e36a385077a2 size=105`

How do I troubleshoot this, am I using the right nugets? 
```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
<PackageReference Include="Microsoft.Azure.DurableTask.Netherite.AzureFunctions" Version="1.4.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.13.0" />
```

Any tips to troubleshoot this would be very helpful.

Edit: Storage I have configured is Standard SKU / StorageV2

**Comment by sebastianburckhardt** [comment]
We added these warnings to help us identify situations where peformance is impacted by high storage latencies. There are many reasons that can cause high storage latency.

Seeing a few of these performance warnings here and there is pretty normal, and not something to worry about. Even under normal circumstances Azure storage service calls can exhibit high "tail" latencies, meaning that a small number of requests "randomly" just take a very long time.

If you see *very many* of these warnings, and/or *very high* reported latencies, it may indicate your system is struggling, perhaps experiencing high load, low memory, or network contention.

To prevent these warnings from being displayed in the console or being collected by ApplicationInsights, add/modify this line of `host.json`:
```
"version": "2.0",
  "logging": {
    "logLevel": {
      "DurableTask.Netherite.FasterStorage.Performance": "Error",
    },
```

**Comment by kvattikuti** [comment]
Thank you. May I ask if you have any opinion about using Standard vs Premium storage for netherite based durable functions?

**Comment by sebastianburckhardt** [comment]
At the moment we do not support Premium Storage. The reason is that premium storage handles page blob allocation and billing differently than standard storage, and Netherite heavily uses page blobs.

**Comment by sebastianburckhardt** [comment]
Closing this since the question appears to have been answered.
