### ISSUE TITLE
Try to connect with DurableFunctionsMonitor

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#38]
https://github.com/scale-tone/DurableFunctionsMonitor

**Comment by scale-tone** [comment]
It turned out that DfMon works with both new storage providers out-of-the-box already. Just use it in 'injected' mode, by adding DurableFunctionsMonitor.DotNetBackend NuGet package to _your_ project (which should be configured to use either Netherite or MSSQL) and add a bit of initialization code as described here: https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetBackend/.

I'm planning to use the same strategy for enabling it to work under VsCode extension as well - we'll just have separate backends (that only have the proper config in them and pull the main package from NuGet dynamically)

**Comment by scale-tone** [comment]
Only problem is that Netherite wants to see at least one orchestration/entity in the current project. With no orchestrations/entities defined DurableOrchestrationClient.ListInstancesAsync() throws the following: 
`System.Private.CoreLib: Exception while executing function: DfmGetOrchestrationFunction. DurableTask.Netherite: Object reference not set to an instance of an object.`

**Comment by sebastianburckhardt** [comment]
Right, I remember running into this problem.

It appears that DF does not call StartAsync() on the orchestration service unless there is a DF trigger in the application. Because the service is never started I run into the null reference later on.

I will need to figure out how to work around that.

**Comment by scale-tone** [comment]
> It appears that DF does not call StartAsync() on the orchestration service unless there is a DF trigger in the application. Because the service is never started I run into the null reference later on.

Yeah, this appears to be a real problem for DfMon :(  In standalone mode (when DfMon runs as a separate Function instance) we in fact *don't want* that orchestration service to get started. Because otherwise this DfMon instance will interfere with the running app and lead to a disaster.

Just to mention that MSSQL storage provider doesn't have this issue (or at least, I didn't notice any visible implications).

**Comment by sebastianburckhardt** [comment]
> we in fact don't want that orchestration service to get started

The idea with Netherite was to start/stop the orchestration service even if you are using it only as a client, there is a configuration setting for "client-only" mode. 

I can probably change that. For example, I could just lazily construct a client if you call Netherite and it hasn't been constructed yet. I am not completely happy with this because then I can't use StopAsync to clean things up. EventHubs is not happy if you leave too many receivers open.

**Comment by scale-tone** [comment]
> there is a configuration setting for "client-only" mode.

What kind of setting is that?

**Comment by sebastianburckhardt** [comment]
It's a field of `NetheriteOrchestrationServiceSettings` called `PartitionManagement` and it can be set to `ClientOnly`.
 
It can also be set in host.json:
```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "storageProvider": {
        "type": "Netherite",
        "StorageConnectionName": "AzureWebJobsStorage",
        "EventHubsConnectionName": "EventHubsConnection",
        "PartitionManagement": "ClientOnly"
      }
    }
  }
}
```

**Comment by scale-tone** [comment]
> It's a field of NetheriteOrchestrationServiceSettings called PartitionManagement and it can be set to ClientOnly

Setting that to `ClientOnly` causes DurableOrchestrationClient.ListInstancesAsync() method to hang for 15 minutes and then throw the following:
```
[2021-06-06T21:40:10.158Z] Executed 'DfmGetOrchestrationsFunction' (Failed, Id=53746c4b-7a79-42ce-a0b8-bf0dd5f7b88d, Duration=299002ms)
[2021-06-06T21:40:10.167Z] System.Private.CoreLib: Exception while executing function: DfmGetOrchestrationsFunction. System.Private.CoreLib: One or more errors occurred. (Client request timed out.). System.Private.CoreLib: Client request timed out.
[2021-06-06T21:41:16.073Z] Executed 'DfmGetOrchestrationsFunction' (Failed, Id=9d9344d0-8c3d-4a4c-a047-ce31f01f31de, Duration=299481ms)
[2021-06-06T21:41:16.124Z] System.Private.CoreLib: Exception while executing function: DfmGetOrchestrationsFunction. System.Private.CoreLib: One or more errors occurred. (Client request timed out.). System.Private.CoreLib: Client request timed out.
[2021-06-06T21:43:22.035Z] Executed 'DfmGetOrchestrationsFunction' (Failed, Id=71a0633a-3d64-4d06-9ced-edb335c8b188, Duration=299696ms)
[2021-06-06T21:43:22.057Z] System.Private.CoreLib: Exception while executing function: DfmGetOrchestrationsFunction. System.Private.CoreLib: One or more errors occurred. (Client request timed out.). System.Private.CoreLib: Client request timed out.
```

**Comment by sebastianburckhardt** [comment]
The errors you are seeing are consistent with a situation where you have only a client, but no DF app deployed that can service the client requests (so the client requests time out).  

Unlike SQL or AzureStorage providers, Netherite cannot access storage directly. It requires that the DF app is running.

**Comment by sebastianburckhardt** [comment]
Submitted microsoft/DurableFunctionsMonitor#37
