### ISSUE TITLE
Duplicate Messages from SignalEntityAsync

### ISSUE THREAD

**Issue by alexjebens** [microsoft/durabletask-netherite#394]
We are seeing duplicate messages from starter functions.

```c#
[FunctionName("Process")]
public async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", "patch", "put", Route = null)] HttpRequest req,
    [DurableClient] IDurableEntityClient client)
{
    var process = JsonConvert.DeserializeObject<Process>(await req.ReadAsStringAsync());
    process.Id = Guid.NewGuid().ToString("N");
    await client.SignalEntityAsync<IProcessor>(process.id, o => o.StartProcess(process));
}
```

Our telemetry shows that StartProcess for this id is sometimes triggered twice. Since the id is generated locally the trigger is not issuing the same message by being triggered twice. Since this occurs multiple times per day a Guid collision is extremely unlikely. We are seeing this for functions with HttpTriggers and QueueTriggers.

**Comment by alexjebens** [comment]
The original Pseudocode used process.client instead of process.id

**Comment by sebastianburckhardt** [comment]
I discovered recently that EventHubs can internally duplicate messages, which explains what you are seeing. See https://github.com/microsoft/durabletask-netherite/pull/379 for a discussion. Unfortunately we do not have any mechanism to deduplicate these duplicate deliveries. Your best bet is to implement some form of deduplication yourself.
