### ISSUE TITLE
JSON Deserialization Issue

### ISSUE THREAD

**Issue by JackSkylark** [microsoft/durabletask-netherite#44]
The netherite backend is consistently throwing an InvalidOperationException during startup. Tracing this, I've found that in the method `CheckStorageFormat` in the `BlobManager` expects to receive JSON in capitalized camel case (e.g. `UseAlternateObjectStore`). However, the `taskhubparameters.json` it is reading from is returning as lower case camel case. This is causing Newtonsoft to throw an invalid exception.

I'm not currently changing any of the default Newtonsoft.Json serialization settings. Are there Newtonsoft.Json defaults that are expected? Should Netherite prepare for this by providing it's expected serialization settings when performing serialization / deserialization?

In order to get around this issue, I've manually updated the JSON in `taskhubparameters.json` to be in the format expected in code. But, I am unsure if this will have any other downstream effects.

**Comment by sebastianburckhardt** [comment]
Interesting. This does not happen in my environment. Something about how I serialize this must be non-robust, i.e. happen differently on different environments. Like you suggest, the best solution is probably for Netherite to exert more explicit control over how Newtonsoft  does the serialization, which should prevent this problem.

Though, I would sill like to repro so I can validate the fix. What environment are you running this on?

> I've manually updated the JSON in taskhubparameters.json to be in the format expected in code. But, I am unsure if this will have any other downstream effects.

This should not have any negative effects later on.

**Comment by sebastianburckhardt** [comment]
This has gone out with the latest release 0.4.0-alpha.
