### ISSUE TITLE
Handling Partial TaskHub Deletion

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#48]
A TaskHub can go into a "partially deleted" state if its EventHubs are deleted, but its TaskHub data is left in storage.

This is never supposed to happen; it is a "resource management error" to delete the EventHubs without also deleting the TaskHub. That said, it is a not an unlikely error thus we need to handle it in some graceful way.

In principle, I see several options:
1. Create an error message saying that the taskhub is broken and needs to be deleted.
2. Create a warning, delete the taskhub, and recreate it.
3. Try to recover and recreate the EventHubs.

While 3. sounds the nicest it is not possible to recover in all cases since the whole architecture fundamentally relies on messages not being lost. So only the first two are real options. I suppose I prefer 1. because it is the most likely to make the user understand what went wrong and actually fix the root cause.

@davidmrdavid, do you have any suggestions on this?

**Comment by davidmrdavid** [comment]
**Just for context, is this the same issue I was experiencing locally when changing my EventHubs connection string but re-using the same TaskHub ID?** If so, I agree that displaying an error message explaining what went wrong and how to fix it is best; trying to fix it on behalf of the user might be dangerous anyways.

However, _assuming_ this is the same issue I was experiencing locally, I worry that that VSCode users might run into this issue quite frequently. In VSCode, if you're using the Azure Functions gestures to quickly scaffold your application, you will re-use the same default **local TaskHub** for all newly created apps. In most cases, this is something you don't need to think about, but here it appears to be quite important.

I some ideas on what to do about that, but I first want to make sure this ticket is referring to the issue I experienced. Please let me know, I wasn't certain from the description.

**Comment by sebastianburckhardt** [comment]
Yes, it is the same issue.

With Netherite, a "taskhub" has two pieces: the queues (in EventHubs) and the store (in AzureStorage). These pieces are not separable, i.e.  once created a Taskhub must always use the same queues and partition count. 

To detect this error I would store the namespace info in the taskhub.json file and check that it matches.

**Comment by davidmrdavid** [comment]
I see, thank you for clarifying. In that case, I continue supporting option 1.

As for the contents of the error message, I think it should make it clear that the customer has, at least, two options: (1) to change the taskhub name in `host.json` or (2) to replace the eventHubs connection string with the expected one.

I would also suggest calling out this requirement explicitly in the docs, especially here: https://microsoft.github.io/durabletask-netherite/#/settings

**Comment by sebastianburckhardt** [comment]
Is addressed in #59.

**Comment by davidmrdavid** [comment]
Fantastic! Seems like the only missing bit is then to update the documentation to call this out, so folks don't have to rely on the error message in the first place :)

**Comment by sebastianburckhardt** [comment]
Added docs.

**Comment by sebastianburckhardt** [comment]
With #130 we can now gracefully handle and automatically recover from the partially deleted state.
