### ISSUE TITLE
Netherite breaks due to dll load error

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#55]
## Observed Exception

When recovering a partition after an ungraceful shutdown Netherite can hit this exception:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Channels, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Threading.Channels, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at DurableTask.Netherite.Faster.LogWorker.ReplayCommitLog(Int64 from, StoreWorker worker)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DurableTask.Netherite.Faster.LogWorker.ReplayCommitLog(Int64 from, StoreWorker worker)
   at DurableTask.Netherite.Faster.StoreWorker.ReplayCommitLog(LogWorker logWorker) in C:\source\durabletask-netherite\src\DurableTask.Netherite\StorageProviders\Faster\StoreWorker.cs:line 418
   at DurableTask.Netherite.Faster.FasterStorage.CreateOrRestoreAsync(Partition partition, IPartitionErrorHandler errorHandler, Int64 firstInputQueuePosition) in C:\source\durabletask-netherite\src\DurableTask.Netherite\StorageProviders\Faster\FasterStorage.cs:line 159

This will effectively prevent Netherite from making any progress and it goes into an infinite recycle.

## Repro
.Net Windows EP3. The DF Template from VS w/ zero changes other than setting extension settings to enable netherite/sql and then the app settings to wire them up.

## Proposed solution

Two things to consider:
1. We nee to solve the dll problem. There is a chance that moving to the latest dependencies could help here.
2. We need to make the problem more observable. I am thinking of (a) forcing early load of this dll, not just at recovery time, and (b) making the load error more observable in the portal, for example as a failure to start function app that creates a visible message.

**Comment by sebastianburckhardt** [comment]
This seems to be a problem with the tooling in Microsoft.NET.Sdk.Functions.

As a temporary workaround, installing an older version (such as 3.0.1) of Microsoft.NET.Sdk.Functions fixes the problem.

**Comment by shibayan** [comment]
I've encountered this problem and wrote an additional workaround. Since the Function SDK removes dlls that the runtime has in advance from the deployment package, referring to package `v5.0.0` will cause a version mismatch and throw exception.

1. Add `_FunctionsSkipCleanOutput`

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
</Project>
```

2. Add `FunctionsPreservedDependencies`

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Threading.Channels.dll" />
  </ItemGroup>
</Project>
```

3. Downgrade of `Microsoft.NET.Sdk.Functions` to `v3.0.3`
4. Downgrade of `System.Threading.Channels` referenced by Netherite to `v4.7.1`.

I recommend downgrading the version of `System.Threading.Channels`. (if possible)

**Comment by sebastianburckhardt** [comment]
I agree that downgrading `System.Threading.Channels` is the best workaround. The code currently has some dependencies on methods that were introduced in 5.0.0, so it is not a trivial downgrade, but it looks easy enough so I will try that next.
