### ISSUE TITLE
Support composite connection string

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#81]
Currently, the configuration requires two separate connection strings for storage and eventhubs. This creates issues when trying to handle all DT/DF backends in a uniform way, because the other backends only have a single connection string.

To fix this, as discussed with @ConnorMcMahon, the idea is to use a composite connection string which has key-value pairs (which is a standard thing, see https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings).

Specifically, we introduce a new configuration setting called "ConnectionString" which can be

*  `storage=AzureWebJobsStorage;transport=EventHubsConnection`     
   use connection names AzureWebJobsStorage and EventHubsConnection for connecting to the respective services
   this is also the default setting
*  `storage=AzureWebJobsStorage;transport=emulated`     
   uses the supplied storage, but emulates the event hubs
*  `storage=emulated;transport=emulated`   
   emulates both the storage and eventhubs

**Comment by ConnorMcMahon** [comment]
I think this works, as long as we **very** clearly document it. I think we are fine with having key-value pairs separated by `;`, because the values in those key value pairs should be app settings, which I think cannot contain semi-colons (I will double check this).

**Comment by sebastianburckhardt** [comment]
We have this working now, using simple comma-separated pairs. Needs to be documented.

**Comment by sebastianburckhardt** [comment]
Added documentation.
