### ISSUE TITLE
Proposal for Enhancement of Sample Documentation - recorded walk through 

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/durabletask-netherite#85]
Proposal: The documentation of the sample  can be enhanced by a walk-through recording how to move from Azure Storage to Netherite following the steps of the "Hello" sample description. 

I have recorded one that you find here: [Migrate your Durable Function to Netherite](https://youtu.be/GRcHeZkmVcM).

In case you think that this adds value when referenced in the sample documentation <https://github.com/microsoft/durabletask-netherite/blob/gh-pages/docs/hello-sample.md>, I can prepare a pull request for this proposed enhancement.

**Comment by sebastianburckhardt** [comment]
Nice work, thanks! This definitely adds value. By all means, create a pull request.

**Comment by lechnerc77** [comment]
Great to hear that. Pull request #86 contains a proposal for the sample documentation

**Comment by lechnerc77** [comment]
As the pull request was merged I close the issue - many thanks!
